# Generated by Django 2.1.2 on 2018-11-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('tamano', models.CharField(choices=[('XS', 'Extra pequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra grande')], default='M', max_length=2)),
                ('peso', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('fechaRescate', models.DateField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Rescatado', 'Rescatado'), ('Adoptado', 'Adoptado')], default='Rescatado', max_length=10)),
            ],
        ),
    ]
